apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-rep
  labels:
    app: my-k8s-app
    env: prod
    owner: me
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
      - name: cia-web
        image: ioc0kernel/sicmtstub:002
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
