apiVersion: v1
kind: Pod
metadata:
  name: my-api
  labels:
   env: test
   app: mintrans-stub-api
   tier: backend
   owner: AlexKub
spec:
  containers:
    - name: mintrans-stub-api
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
